env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - id: nowin-cli
    main: ./cmd/client/
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - BUILD=`date +%FT%T%z`
      - COMMIT_SHA1=`git rev-parse HEAD`
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version=${COMMIT_SHA1}|${BUILD}
  - id: win-cli
    main: ./cmd/client/
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - BUILD=`date +%FT%T%z`
      - COMMIT_SHA1=`git rev-parse HEAD`
    goos:
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version=${COMMIT_SHA1}|${BUILD}
  - id: nowin-server
    main: ./cmd/server/
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - BUILD=`date +%FT%T%z`
      - COMMIT_SHA1=`git rev-parse HEAD`
    goos:
      - linux
      - darwin
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: '386'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version=${COMMIT_SHA1}|${BUILD}
  - id: win-server
    main: ./cmd/server/
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - BUILD=`date +%FT%T%z`
      - COMMIT_SHA1=`git rev-parse HEAD`
    goos:
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version=${COMMIT_SHA1}|${BUILD}

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: binary-cli
    builds:
      - win-cli
    name_template: "{{ .ProjectName }}_cli_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary
  - id: nowin-cli
    builds:
      - nowin-cli
      - win-cli
    name_template: "{{ .ProjectName }}_cli_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
  - id: binary-server
    builds:
      - win-server
    name_template: "{{ .ProjectName }}_server_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: binary
  - id: nowin-server
    builds:
      - nowin-server
      - win-server
    name_template: "{{ .ProjectName }}_server_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
